version: '3.8'

services:
    bookings:
        build: ./bookings
        volumes:
            - ./database.sqlite:/home/app/database.sqlite
        working_dir: /home/app
        command: sh -c "npm install sqlite3 --save && npm start"

    hotels:
        build: ./hotels
        volumes:
            - ./database.sqlite:/home/app/database.sqlite
        working_dir: /home/app
        command: sh -c "npm install sqlite3 --save && npm start"

    nginx:
        image: nginx:1.21-alpine-perl
        depends_on:
            - bookings
            - hotels
        volumes:
            - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
        ports:
            - '80:80'
