version: "3.8"

volumes:
  db_data: {}

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432

  booking_backend:
    container_name: lr3_booking_express
    build: ./booking
    command: bash -c "npm run migration:run && npm run start"
    volumes:
      - ./booking:/app
    ports:
      - "4001:4000"
    depends_on:
      - db

  hotels_backend:
    container_name: lr3_hotels_express
    build: ./hotels
    command: bash -c "npm run migration:run && npm run start"
    volumes:
      - ./hotels:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
