http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: '/auth/*'
  flight:
    host: localhost
    paths: ['/flights', '/flights/*']
  ticket:
    host: localhost
    paths: ['/tickets', '/tickets/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authService:
    url: 'http://localhost:3000'
  flightService:
    url: 'http://localhost:3001'
  ticketService:
    url: 'http://localhost:3002'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  flightPipeline:
    apiEndpoints:
      - flight
    policies:
      - proxy:
          - action:
              serviceEndpoint: flightService
              changeOrigin: true
  ticketPipeline:
    apiEndpoints:
      - ticket
    policies:
      - proxy:
          - action:
              serviceEndpoint: ticketService
              changeOrigin: true