version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  post:
    build:
      context: .
      dockerfile: ./src/microservices/PostService/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8081:8081"
