version: '3'
services:

  db:
    image: postgres:13
    volumes:
      - /var/lib/postgresql/13/main
    env_file:
      - .env
    ports:
      - 5432

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8002:8002"
    depends_on:
      - "db"
    volumes:
      - .:/app

  hotels:
    build:
      dockerfile: Dockerfile
      context: ./hotels
    container_name: hotels
    ports:
      - "8001:8001"
    depends_on:
      - "db"
    volumes:
      - .:/app