http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  user:
    host: localhost
    paths: '/auth/*'
  flightticket:
    host: localhost
    paths: ['/flights', '/tickets', '/tickets/*', '/flights/*']
serviceEndpoints:
  userService:
    url: 'http://user:7777/'
  flightticketService:
    url: 'http://flight_ticket:7778/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  flightticketPipeline:
    apiEndpoints:
      - flightticket
    policies:
      - proxy:
          - action:
              serviceEndpoint: flightticketService
              changeOrigin: true